# 端口
server:
  port: 0

# 应用名-注册的服务名
spring:
  application:
    name: ribbon-consumer
  cloud:
    loadbalancer:
      retry:
        # 开启重试机制
        enabled: true
  #设置时间格式和时间地区
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# 指定服务注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
    # 是否获取服务：默认true
    fetch-registry: true
    # 消费者缓存清单更新时间：默认30s
    registry-fetch-interval-seconds: 30
  instance:
    # 注册eureka的应用名
    appname: ribbon-consumer
    # 手动指定区域 2.0版本由原先的String升级为Map<String,String>,key有待研究
#    metadata-map:
#      default: hangzhou
    # 设置实例名
    instance-id: ${spring.application.name}:${random.int(1000,1999)}

# 在无服务治理框架下，需要指定服务名的实例清单
# 禁用eureka对ribbon的维护
#ribbon:
#  eureka:
#    enable: false
#hello-service:
#  ribbon:
#    listOfServers: localhost:63475,localhost:63484
#    # 重试机制配置
#    # 请求连接的超时时间
#    ConnectTimeout: 250
#    # 请求处理的超时时间
#    ReadTimeout: 1000
#    # 对所有请求都进行重试
#    OkToRetryOnAllOperations: true
#    # 切换实例的重试次数
#    MaxAutoRetriesNextServer: 2
#    # 当前实例的重试次数
#    MaxAutoRetries: 1

# 断路器超时时间需要大于Ribbon的超时时间，不然不会触发重试
#hypermedia:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 10000






