# 端口
server.port: 9000

# 应用名-注册的服务名
spring:
  application:
    name: ribbon-consumer

# 指定服务注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
    # 是否获取服务：默认true
    fetch-registry: true
    # 消费者缓存清单更新时间：默认30s
    registry-fetch-interval-seconds: 30
  instance:
    # 注册eureka的应用名
    appname: ribbon-consumer


