# 端口
spring:
  application:
    name: turbin

# 应用名-注册的服务名
server:
  port: 8989

# management server 端口
management:
  server:
    port: 8990

# 指定服务注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/

# 与消息代理 RabbitMQ 结合有待后续实现
turbine:
  # 指定需要收集监控信息的服务名
  app-config: RIBBON-CONSUMER
  # 集群名称为 default，当服务非常多的时候，可以启动多个 Turbine 服务构建不同的聚合集群，该参数可以用来区分这些不同的聚合集群。
  # 只需在 Hystrix Stream 的 URL 中，通过 cluster 参数指定
  # 惊呆了，竟然有这种操作，写 default 不行，竟然要写 new String("default")
  cluster-name-expression: new String("default")
  # 让同一主机上的服务通过主机名与端口号组合进行区分，
  combine-host-port: true