# 自定义属性(可以通过上下文的方式引用)
book:
  name: SpringClouldInAction
  author: Jeferry
  desc: ${book.author} is writing 《${book.name}》 in dev

# ${random} 产生随机数
com:
  jeferry:
    # 随机字符串
    value: ${random.value}
    # 随机int
    number: ${random.int}
    # 随机long
    bigNumber: ${random.long}
    # 10以内随机int
    tinyInt: ${random.int(10)}
    # 10-20随机数
    randomValue: ${random.int(10,20)}