# 端口
server.port: ${random.int(1000,1999)}

# 应用名-注册的服务名
spring:
  application:
    name: hello-service
  profiles:
    active: dev # 定义应用环境-决定加载哪个application-${spring.profiles.active}.yml配置文件

# 指定服务注册中心地址
eureka:
  client:
    # 自定义region，一个微服务只能属于一个region。默认default
    region: default
    # 自定义Zone，默认defaultZone。region和zone一对多，zone为Map
    availability-zones:
      defaultZone1: http://peer1:1111/eureka/
      defaultZone2: http://peer2:1112/eureka/
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
#      安全起见，可以加入用户名和密码校验
#      defaultZone: http://<userName>:<password>@peer1:1111/eureka/,http://peer2:1112/eureka/
  instance:
    appname: hello-service
    # 服务续约任务间隔：默认30s
    lease-renewal-interval-in-seconds: 30
    # 服务失效时间：默认90s
    lease-expiration-duration-in-seconds: 90
    # 设置实例名
    instance-id: ${spring.application.name}:${random.int}

# actuator info端点信息，访问URI：/actuator/info
info:
  app:
    name: spring-boot-hello
    version: 0.0.1-SNAPSHOT
    active: ${spring.profiles.active}

# ${random} 产生随机数
com:
  jeferry:
    # 随机字符串
    value: ${random.value}
    # 随机int
    number: ${random.int}
    # 随机long
    bigNumber: ${random.long}
    # 10以内随机int
    tinyInt: ${random.int(10)}
    # 10-20随机数
    randomValue: ${random.int(10,20)}

