# 端口
server.port: 8081

# 应用名-注册的服务名
spring:
  application:
    name: hello-service
  profiles:
    active: dev # 定义应用环境-决定加载哪个application-${spring.profiles.active}.yml配置文件

# 指定服务注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
  # 注册eureka的应用名
  instance:
    appname: hello-service

# actuator info端点信息，访问URI：/actuator/info
info:
  app:
    name: spring-boot-hello
    version: 0.0.1-SNAPSHOT
    active: ${spring.profiles.active}

# ${random} 产生随机数
com:
  jeferry:
    # 随机字符串
    value: ${random.value}
    # 随机int
    number: ${random.int}
    # 随机long
    bigNumber: ${random.long}
    # 10以内随机int
    tinyInt: ${random.int(10)}
    # 10-20随机数
    randomValue: ${random.int(10,20)}

